In [8]:
from diffusion_libs import get_network, DiffusionModel, scale_dataset
from samples_generators import fill_vocabulary_c_v1, convert_back_to_code_c_v1, vocabulary_c_v1
import tensorflow as tf
from tensorflow import keras
import numpy as np
import tensorflow as tf

In [13]:
fill_vocabulary_c_v1()
# sampling
min_signal_rate = 0.02
max_signal_rate = 0.95

# architecture
embedding_dims = 32
embedding_max_frequency = 1000.0
embedding_min_frequency = 1.0

# optimization
batch_size = 16
ema = 0.999
learning_rate = 1e-3

# dictionary related
DICTIONARY_SIZE = len(vocabulary_c_v1)
TOKENS_CAPACITY = 256

widths = [64, 64, 96, 128]
block_depth = 2

lang_base = f"E:\Studies\master_thesis\diffusion_models_checpoints_savespace\D11-02-2023\simple_c_v1"
model_path = f"{lang_base}\cp-0032\model"

Dictionary already filled


In [14]:
network = get_network(
      TOKENS_CAPACITY, embedding_min_frequency, embedding_max_frequency, 
      embedding_dims, widths=widths, block_depth=block_depth, name="complicated"
  )

model = DiffusionModel(
      TOKENS_CAPACITY, DICTIONARY_SIZE, network, batch_size, max_signal_rate, 
      min_signal_rate, ema, False
  )

model.compile(
    optimizer = keras.optimizers.experimental.Adam(
        learning_rate=learning_rate
    ),
    loss = keras.losses.mean_absolute_error
)

#normalizer
n_w = np.load(f"{lang_base}\\normalizer_weights.npy", allow_pickle=True)
normalizer = keras.layers.Normalization(mean=n_w[0], variance=n_w[1])
normalizer.build((TOKENS_CAPACITY))
model.normalizer = normalizer
model.load_weights(model_path)

### First should generate some sample to see if it still generates something that looks like code

In [17]:
raw, denormalized = model.generate(5,100)
for sample in denormalized:
  scaled = scale_dataset(sample, DICTIONARY_SIZE)
  print(" ".join(convert_back_to_code_c_v1(scaled)).replace(";", ";\n").replace("{", "{\n").replace("}", "}\n"))
  print()

int ID0 ( char ID1 , char ID2 ) {
 int ID3 ;
 ID2 = STRING ;
 int ID4 = STRING / NUM / NUM / STRING ;
 int ID5 ;
 ID4 = ID3 / ID2 / ID1 - ID3 + STRING + STRING ;
 ID5 = ID2 / NUM ;
 printf ( STRING , ID3 ) ;
 ID4 = char ;
 printf ( STRING , ID6 ) ;
 printf ( STRING , ID2 ) ;
 ID3 & ID5 + ID4 + char ) ID3 & ID3 - char - ID2 scanf int ) ID3 & ID2 scanf int - int scanf int / int scanf int - int ) ID4 & ID3 scanf int printf ID1 scanf int ) NUM & void }
 ID3 ( printf int ) {
 }
 }
 }
 }
 EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EM

In [40]:
scaled = scale_dataset(denormalized[len(denormalized) - 1], DICTIONARY_SIZE)
convs = convert_back_to_code_c_v1(scaled)
n = 5
chunked = [convs[i:i + n] for i in range(0, len(convs), n)]
for symbols in chunked:
  print(" ".join(symbols))

char ID0 ( char ID1
, char ID2 , int
ID3 ) { scanf (
STRING , ID2 ) ;
int ID4 = ID2 *
STRING + NUM / ID2
+ STRING ; int ID5
; char ID6 = ID2
/ ID3 / ID5 *
ID3 / NUM ; scanf
( STRING , NUM )
; int ID7 ; ID2
= ID5 + ID4 /
STRING ; char ID7 ;
return NUM ; } EMPTY
EMPTY EMPTY EMPTY EMPTY EMPTY
EMPTY EMPTY EMPTY EMPTY EMPTY
EMPTY EMPTY EMPTY EMPTY EMPTY
EMPTY EMPTY EMPTY EMPTY EMPTY
EMPTY EMPTY EMPTY EMPTY EMPTY
EMPTY EMPTY EMPTY EMPTY EMPTY
EMPTY EMPTY EMPTY EMPTY EMPTY
EMPTY EMPTY EMPTY EMPTY EMPTY
EMPTY EMPTY EMPTY EMPTY EMPTY
EMPTY EMPTY EMPTY EMPTY EMPTY
EMPTY EMPTY EMPTY EMPTY EMPTY
EMPTY EMPTY EMPTY EMPTY EMPTY
EMPTY EMPTY EMPTY EMPTY EMPTY
EMPTY EMPTY EMPTY EMPTY EMPTY
EMPTY EMPTY EMPTY EMPTY EMPTY
EMPTY EMPTY EMPTY EMPTY EMPTY
EMPTY EMPTY EMPTY EMPTY EMPTY
EMPTY EMPTY EMPTY EMPTY EMPTY
EMPTY EMPTY EMPTY EMPTY EMPTY
EMPTY EMPTY EMPTY EMPTY EMPTY
EMPTY EMPTY EMPTY EMPTY EMPTY
EMPTY EMPTY EMPTY EMPTY EMPTY
EMPTY EMPTY EMPTY EMPTY EMPTY
EMPTY EMPTY EMPTY EMPTY EMPTY
EMPTY EMPTY EMPTY E

In [45]:
l = np.around(denormalized[len(denormalized) - 1], 3).tolist()
chunked = [l[i:i + n] for i in range(0, len(l), n)]
for symbols in chunked:
  print(np.around(np.asarray(symbols), 3))

[0.055 0.583 0.389 0.048 0.611]
[0.56  0.053 0.643 0.56  0.039]
[0.665 0.424 0.474 0.188 0.383]
[0.079 0.553 0.64  0.413 0.445]
[0.039 0.692 0.364 0.632 0.292]
[0.097 0.244 0.101 0.274 0.626]
[0.248 0.093 0.442 0.041 0.709]
[0.447 0.054 0.744 0.364 0.63 ]
[0.273 0.665 0.287 0.722 0.293]
[0.662 0.268 0.101 0.441 0.194]
[0.392 0.092 0.551 0.097 0.416]
[0.44  0.027 0.779 0.447 0.653]
[0.359 0.71  0.242 0.691 0.273]
[0.095 0.44  0.046 0.781 0.451]
[0.139 0.119 0.451 0.506 0.533]
[0.527 0.527 0.524 0.523 0.522]
[0.53  0.529 0.528 0.533 0.529]
[0.525 0.524 0.525 0.526 0.522]
[0.523 0.529 0.524 0.528 0.523]
[0.531 0.526 0.53  0.525 0.528]
[0.528 0.527 0.528 0.53  0.525]
[0.528 0.525 0.526 0.529 0.527]
[0.53  0.525 0.526 0.524 0.527]
[0.528 0.527 0.528 0.526 0.529]
[0.529 0.529 0.528 0.525 0.53 ]
[0.529 0.526 0.529 0.527 0.527]
[0.524 0.528 0.527 0.527 0.524]
[0.528 0.522 0.524 0.524 0.528]
[0.524 0.529 0.524 0.526 0.525]
[0.525 0.521 0.526 0.522 0.525]
[0.527 0.525 0.523 0.524 0.527]
[0.525 0