In [1]:
from diffusion_libs import get_network, DiffusionModel, scale_dataset
from samples_generators import fill_vocabulary_c_v2, convert_back_to_code_c_v2, vocabulary_c_v2
import tensorflow as tf
from tensorflow import keras
import numpy as np
import tensorflow as tf

In [4]:
fill_vocabulary_c_v2()
# sampling
min_signal_rate = 0.02
max_signal_rate = 0.95

# architecture
embedding_dims = 32
embedding_max_frequency = 1000.0
embedding_min_frequency = 1.0

# optimization
batch_size = 16
ema = 0.999
learning_rate = 1e-3

# dictionary related
DICTIONARY_SIZE = len(vocabulary_c_v2)
TOKENS_CAPACITY = 256

widths = [64, 64, 96, 128, 256]
block_depth = 2

lang_base = f"E:\Studies\master_thesis\diffusion_models_checpoints_savespace\\final_checkpoints\simple_c_v3"
model_path = f"{lang_base}\cp-0128\model"

Dictionary already filled


In [5]:
network = get_network(
      TOKENS_CAPACITY, embedding_min_frequency, embedding_max_frequency, 
      embedding_dims, widths=widths, block_depth=block_depth, name="complicated"
  )

model = DiffusionModel(
      TOKENS_CAPACITY, DICTIONARY_SIZE, network, batch_size, max_signal_rate, 
      min_signal_rate, ema, False
  )

model.compile(
    optimizer = keras.optimizers.experimental.Adam(
        learning_rate=learning_rate
    ),
    loss = keras.losses.mean_absolute_error
)

#normalizer
n_w = np.load(f"{lang_base}\\normalizer_weights.npy", allow_pickle=True)
normalizer = keras.layers.Normalization(mean=n_w[0], variance=n_w[1])
normalizer.build((TOKENS_CAPACITY))
model.normalizer = normalizer
model.load_weights(model_path)

### First should generate some sample to see if it still generates something that looks like code

In [6]:
raw, denormalized = model.generate(5,100)
for sample in denormalized:
  scaled = scale_dataset(sample, DICTIONARY_SIZE)
  print(" ".join(convert_back_to_code_c_v2(scaled)).replace(";", ";\n").replace("{", "{\n").replace("}", "}\n"))
  print()

int ID0 ( char ID1 , int ID2 ) {
 char ID3 = STRING + STRING / STRING & ID3 & ID1 + STRING ;
 int ID5 = NUM + ID3 / STRING ;
 int ID6 ;
 scanf ( STRING , ID4 ) ;
 ID5 = STRING + STRING ;
 ID4 = NUM / STRING + NUM ;
 ID2 = ID3 + ID4 + STRING + STRING ;
 scanf ( STRING , STRING ) ;
 ID3 = STRING ;
 ID6 = ID5 / STRING ;
 if ( ID5 < = NUM ) {
 int ID7 ( ID2 + NUM {
 ID0 > ;
 scanf ( STRING , NUM ) ;
 }
 return NUM ;
 }
 EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPT

In [9]:
scaled = scale_dataset(denormalized[len(denormalized) - 3], DICTIONARY_SIZE)
convs = convert_back_to_code_c_v2(scaled)
n = 5
chunked = [convs[i:i + n] for i in range(0, len(convs), n)]
for symbols in chunked:
  print(" ".join(symbols))

int ID0 ( char ID1
, char ID2 ) {
char ID3 = STRING +
STRING / STRING ; char
ID4 ; char ID5 =
ID3 / STRING ; char
ID6 ; scanf ( STRING
, ID5 ) ; ID3
= STRING / ID4 /
ID4 / STRING ; if
( ID5 / ID6 <
= NUM ) { char
ID7 ; scanf ( STRING
, STRING ) ; ID8
= STRING ; } return
NUM ; } EMPTY EMPTY
EMPTY EMPTY EMPTY EMPTY EMPTY
EMPTY EMPTY EMPTY EMPTY EMPTY
EMPTY EMPTY EMPTY EMPTY EMPTY
EMPTY EMPTY EMPTY EMPTY EMPTY
EMPTY EMPTY EMPTY EMPTY EMPTY
EMPTY EMPTY EMPTY EMPTY EMPTY
EMPTY EMPTY EMPTY EMPTY EMPTY
EMPTY EMPTY EMPTY EMPTY EMPTY
EMPTY EMPTY EMPTY EMPTY EMPTY
EMPTY EMPTY EMPTY EMPTY EMPTY
EMPTY EMPTY EMPTY EMPTY EMPTY
EMPTY EMPTY EMPTY EMPTY EMPTY
EMPTY EMPTY EMPTY EMPTY EMPTY
EMPTY EMPTY EMPTY EMPTY EMPTY
EMPTY EMPTY EMPTY EMPTY EMPTY
EMPTY EMPTY EMPTY EMPTY EMPTY
EMPTY EMPTY EMPTY EMPTY EMPTY
EMPTY EMPTY EMPTY EMPTY EMPTY
EMPTY EMPTY EMPTY EMPTY EMPTY
EMPTY EMPTY EMPTY EMPTY EMPTY
EMPTY EMPTY EMPTY EMPTY EMPTY
EMPTY EMPTY EMPTY EMPTY EMPTY
EMPTY EMPTY EMPTY EMPTY EMPTY
EMPTY EMPTY EMPTY E

In [10]:
l = np.around(denormalized[len(denormalized) - 3], 3).tolist()
chunked = [l[i:i + n] for i in range(0, len(l), n)]
for symbols in chunked:
  print(np.around(np.asarray(symbols), 3))

[0.047 0.643 0.31  0.071 0.664]
[0.427 0.06  0.689 0.333 0.382]
[0.061 0.724 0.286 0.089 0.178]
[0.099 0.179 0.107 0.356 0.061]
[0.734 0.359 0.064 0.761 0.284]
[0.71  0.183 0.102 0.363 0.066]
[0.793 0.359 0.568 0.312 0.09 ]
[0.43  0.762 0.339 0.357 0.719]
[0.284 0.1   0.191 0.736 0.199]
[0.728 0.179 0.106 0.357 0.601]
[0.312 0.757 0.181 0.79  0.467]
[0.283 0.116 0.337 0.373 0.061]
[0.818 0.351 0.566 0.314 0.093]
[0.436 0.1   0.33  0.36  0.826]
[0.281 0.101 0.351 0.404 0.528]
[0.114 0.353 0.407 0.006 0.002]
[0.003 0.004 0.002 0.002 0.001]
[0.002 0.001 0.002 0.002 0.002]
[0.003 0.004 0.001 0.002 0.002]
[0.001 0.001 0.    0.    0.001]
[0.001 0.    0.001 0.    0.   ]
[0.    0.    0.    0.    0.001]
[0.001 0.    0.001 0.001 0.   ]
[0.    0.001 0.001 0.    0.002]
[0.005 0.    0.    0.    0.001]
[0.    0.    0.001 0.    0.001]
[0.001 0.    0.001 0.001 0.001]
[0.    0.    0.    0.    0.001]
[0.001 0.    0.    0.001 0.   ]
[0. 0. 0. 0. 0.]
[0.    0.001 0.    0.    0.   ]
[0.    0.001 0.    0.  